# Generated by Django 4.2.4 on 2023-08-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('profilePicture', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('agency', 'agency'), ('client', 'client')], max_length=100)),
            ],
        ),
    ]
